name: Run get kintone records to show QR code list

on:
  workflow_dispatch: 
  pull_request:

jobs:
  getdata:
    runs-on: ubuntu-latest
    env:
       KINTONE_API_TOKEN: ${{ vars.JNKYKN_KINTONE_API_TOKEN_APPID2 }}
    permissions:
       actions: write
       checks: write
       contents: write
       deployments: write
       id-token: write
       issues: write
       discussions: write
       packages: write
       pages: write
       pull-requests: write
       repository-projects: write
       security-events: write
       statuses: write
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install kintone-api-client
        run: npm install @kintone/rest-api-client
      - name: check need update
        id: check_update
        run: node jobs/checkNeedUpdate.js
      - name: main job(get kintone records and create QRcode list)
        run: node jobs/getKintoneRecords.js
        if: steps.check_update == 'success'
      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'generated'
          git push
        if: steps.diff.outcome == 'failure'
      