name: Run get kintone records to show QR code list

on:
  workflow_dispatch: 
  pull_request:
  #schedule:
  #  - cron: '0 0-9 * * *'  # 9:00 to 18:00 every hour 

jobs:
  getdata:
    runs-on: ubuntu-latest
    env:
       KINTONE_API_TOKEN: ${{ secrets.JNKYKN_KINTONE_API_TOKEN_APPID2 }}
       MY_PRIVATE_TOKEN: ${{ secrets.MY_PERSONAL_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install modules
        run: npm ci
      - name: main job(get kintone records and create QRcode list)
        run: node jobs/getKintoneRecords.js
